# Utiliza una imagen de Ruby on Rails como base
FROM ruby:3.2.0

# Instala dependencias del sistema
RUN apt-get update && apt-get install -y build-essential postgresql-client patch ruby-dev zlib1g-dev liblzma-dev --no-install-recommends

# Instala Yarn usando npm (Node.js ya se instala en el paso anterior)
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
RUN apt-get install -y nodejs
RUN npm install -g yarn

# Configura el directorio de trabajo
WORKDIR /app

# Instala las gemas de Rails
COPY Gemfile Gemfile.lock /app/
RUN bundle check || bundle install

# Copia el resto de los archivos del proyecto
COPY . /app

# Cambia al directorio de herramientas
WORKDIR /app/_keenthemes/tools

# Instala las dependencias de node
RUN yarn install

# Cambia al directorio principal del proyecto
WORKDIR /app

# Expone el puerto 3000
EXPOSE 3000

# Comando por defecto para iniciar el servidor Rails
CMD ["rails", "server", "-b", "0.0.0.0"]